### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by youdontmeanmuch** [Nicc0/Heart-Changer#4]
Whenever a player is death-banned this message is sent in console.

```
[19:40:55 ERROR]: [net.nicc0.heartchanger.listener.PlayerDeathListener] null
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.nicc0.heartchanger.listener.PlayerDeathListener$1.run(PlayerDeathListener.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1475) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: net.minecraft.server.v1_16_R3.CancelledPacketHandleException
[19:40:55 ERROR]: [net.nicc0.heartchanger.listener.PlayerDeathListener] null
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.nicc0.heartchanger.listener.PlayerDeathListener$1.run(PlayerDeathListener.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1475) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"9bdcb9b"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: net.minecraft.server.v1_16_R3.CancelledPacketHandleException
```

**Comment by PureVanillaFrance** [comment]
Hi ! same error on myside !
